# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: Metrics
on:
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Lehoczky
          template: classic
          base: header
          base_indepth: true
          config_octicon: yes
          config_timezone: Europe/Budapest
          optimize: css, xml

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 4
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          plugin_stars: yes
          plugin_stars_limit: 3

          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 0
          plugin_steam_recent_games_limit: 2
          plugin_steam_sections: player,  recently-played
          plugin_steam_user: "76561198031553952"
